### ISSUE TITLE
error with a dependency uuid4

### ISSUE THREAD

**Issue by josevtecarcel** [konsumer/kasa_control#12] opened 2021-04-06 17:23 UTC
I installed Kasa_control normally but when a try to npm run dev there is an error: 
This dependency was not found:
* uuid4 in ./node_modules/kasa_control/build/lib.js
To install it, you can run: npm install --save uuid4 

I installed the dependency but still have the same error.
Any idea?
Thanks

**Comment by konsumer** [comment] 2021-04-06 20:40
I don't have a "dev" script in this repo. Is that something in your code?

**Comment by konsumer** [comment] 2021-04-06 20:41
The uuid4 dep is tracked in my lib, so my first guess is that it's something on your end.

**Comment by konsumer** [comment] 2021-04-06 20:43
What is the exact error you get? How did you install this lib in your thing? Do you have a repo that has the problem?

**Comment by josevtecarcel** [comment] 2021-04-07 08:07
> I don't have a "dev" script in this repo. Is that something in your code?

I try to run Kasa_control on my vuejs  frontend project. 

1. I installed kasa_control by npm (all ok)
2. I coded one of the examples (all code is in my local yet)
3. I run the dev server by npm run server and I have this exactly error:
 ERROR  Failed to compile with 1 error                                                                                                               
This dependency was not found:
* uuid4 in ./node_modules/kasa_control/build/lib.js
To install it, you can run: npm install --save uuid4

I can see the two libraries kasa control and uuid4 but the error is that. 
Any idea?
thanks

**Comment by konsumer** [comment] 2021-04-07 08:20
Again, do you have a repo link? I can't really troubleshoot your issue (which I'm pretty sure is an issue with your app or something else, as this lib works fine in my things.)

**Comment by josevtecarcel** [comment] 2021-04-07 08:24
> Again, do you have a repo link? I can't really troubleshoot your issue (which I'm pretty sure is an issue with your app or something else, as this lib works fine in my things.)

Like I said in point 2 the code is in my local yet and I do not have the repo. 
I also think is a problem with vuejs but maybe someone has the same problem.
Thanks

**Comment by konsumer** [comment] 2021-04-07 08:25
Make a demo repo that can reproduce the issue and I will take a look.

**Comment by konsumer** [comment] 2021-04-07 08:50
Here is a working minimal demo validating everything is working right on my end:
https://github.com/konsumer/kasa_control_demo

As a sidenote, this lib uses node-fetch, across hosts (whcih will not work at all, in a browser) so I'm really not sure how you would use it in a regular Vue thing. It needs to be on the backend. I guess it could be some kind of SSR thing. If you haven't considered this, it might be easiest to just keep it in a separate backend. Again, if I saw some code for what you are trying to do, I could probably give you more specific advice.

**Comment by konsumer** [comment] 2021-04-07 23:20
I think the path you should be looking at is basically "put kasa_control in your backend service, then hit that from your frontend Vue app". With an example app, I could probably help you architecture that, if you can send me an example of what you are trying to do, even though it is very far outside the scope of this library, just because I'm a nice guy :smile: .

I'm going to close this issue, as there is no way for me to reproduce your issue, and it sounds like you are trying to do something you can't do in a browser, in the first place, but feel free to comment more, if you have something for me to look at, or need some more guidance.

**Closed as completed by konsumer** 2021-04-07 23:20 UTC
